# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TheTea' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheTea
pod 'FBSDKCoreKit'  
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKPlacesKit'
pod 'FBSDKMessengerShareKit'
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.0'

end
